name: CI

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or '3.x' for latest [web:16]

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Run app.py
        run: python app.py  # executes your script [web:16][web:21]

      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: GHActions
          cx_tenant: 2bsecure
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
